apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cme-standard-techlead-v3
  labels:
    k8smgmt.io/bindingtype: rolebinding
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - statefulsets/scale
  verbs:
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
